### ISSUE TITLE
Need flat-top SatRday SVG file (right now, it's the hex svg)

### ISSUE THREAD

**Issue by angela-li** [satRdays/assets#1]
Could you upload the correct svg file for this? Additionally, it would be great if the type could be **converted to outlines**, so that individuals who don't have Agency FB on their computers can work with the graphic.

Thanks for the help!

**Comment by ZoeLocke** [comment]
Hi @angela-li, I've updated the text to paths as requested, but I'm not clear on what you're asking for regarding a flat-topped file.

**Comment by angela-li** [comment]
The original SatRdays logo has a hexagon "lying down", as versus the hex sticker, which has the hexagon point at the top (see the difference b/t the png and svg logo file)

**Comment by ZoeLocke** [comment]
The original version was made in error and should have always been pointing up. I guess this comes down to whether the main logo should be updated (corrected) or accepted. @stephlocke, do you have any thoughts on this?

**Comment by angela-li** [comment]
Uh oh, we’re already using the flat top (non-hex) logo for all of our
promotional material. We’re going to stick with it for now, and maybe
design a new one next year for Chicago with a hex.

Wish you all let me know that the original version was the incorrect one
before I printed mugs, signs, and posters with it!

Angela

**Comment by ZoeLocke** [comment]
Sorry, I wasn't aware it was there :(

I'll do you updated flat version ones, and we really should have some with no hex at all (the hex was really just for the sticker)

I'll have those ready for you tomorrow

**Comment by ZoeLocke** [comment]
OK, I've rotated the hex, but I've also made some versions without the hex that can be used in the future.
